package domain;
/**
 * The ECIPlant class represents a special type of Sunflower plant with predefined cost and health values.
 * It can generate a large sun resource and has an additional attribute to track if extra suns have been generated.
 * It extends the Sunflower class.
 * 
 * @version 2024
 */
public class ECIPlant extends Sunflower {
    /**
     * The cost of creating an ECIPlant.
     */
    private static final int COST = 75;

    /**
     * The health points of an ECIPlant.
     */
    private static final int HEALTH = 150;

    /**
     * A flag indicating whether extra suns have been generated by this plant.
     */
    private boolean extraSunsGenerated = false;

    /**
     * Constructs an ECIPlant with predefined health and cost values.
     */
    public ECIPlant() {
        super();
        this.health = HEALTH;
        this.cost = COST;
    }

    /**
     * Generates a large sun resource worth 50 points.
     * 
     * @param lane The lane in which the resource is generated.
     * @return A Resource object representing the generated large sun.
     */
    @Override
    public Resource generateResource(int lane) {
        return new Resource(Resource.BIG_SOL, 50);
    }

    /**
     * Checks if extra suns have been generated by this plant.
     * 
     * @return true if extra suns have been generated, false otherwise.
     */
    public boolean hasGeneratedExtraSuns() {
        return extraSunsGenerated;
    }

    /**
     * Sets the flag indicating whether extra suns have been generated by this plant.
     * 
     * @param flag The new value for the extraSunsGenerated flag.
     */
    public void setExtraSunsGenerated(boolean flag) {
        this.extraSunsGenerated = flag;
    }
}